In [1]:
import json
import copy
import random
import numpy as np
import pandas as pd
import math
from datetime import datetime
import chardet

In [3]:
df = pd.read_csv('./files/2022_2023.csv')

In [4]:
df

,Акредитација,Шифра,Назив,Смерови,Семестри,Семестар,Фонд,Групе Пр,Групе В,Групе Пк,...,Unnamed: 16,Практикум,Unnamed: 18,Напомена,Бр. распоређ. студената 2021,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Основне академске студије 2022,РМ01,Програмирање 1,"1ИБЛФ1(15), АИ.22, МА.0.15, МЛ.0.15, МЛ.22, ММ...",1,Јесењи семестар,2 + 3,4.0,8.0,0.0,...,NaN,NaN,NaN,NaN,248.0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,2 + 3,4.0,8.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,2 + 3,4.0,8.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,2 + 3,4.0,8.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,2 + 3,4.0,8.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
set_of_lecturers = set()
for i in range(df.shape[0]):
    if df.iloc[i]['Предавања'] == df.iloc[i]['Предавања']:
        set_of_lecturers.add(df.iloc[i]['Предавања'])
    if df.iloc[i]['Вежбе'] == df.iloc[i]['Вежбе']:
        set_of_lecturers.add(df.iloc[i]['Вежбе'])
lecturers = pd.DataFrame(set_of_lecturers, columns=["name"])
lecturers['preffered_timeslots'] = np.empty((len(lecturers), 0)).tolist()
lecturers['not_preffered_timeslots'] = np.empty((len(lecturers), 0)).tolist()
lecturers['preffered_locations'] = np.empty((len(lecturers), 0)).tolist()

In [46]:
lecturers

,name,preffered_timeslots,not_preffered_timeslots,preffered_locations
0,Огњен Милинковић,[],[],[]
1,Милена Вујошевић Јаничић,[],[],[]
2,Денис Аличић,[],[],[]
3,Ненад Митић,[],[],[]
4,Стефан Капунац,[],[],[]
5,Ивана Томашевић,[],[],[]
6,Јована Ковачевић,[],[],[]
7,Иван Ристовић,[],[],[]
8,Стефан Мишковић,[],[],[]
9,Филип Марић,[],[],[]
10,Филип Видојевић,[],[],[]
11,Петар Ђорђевић,[],[],[]
12,Јелена Марковић,[],[],[]
13,Предраг Јаничић,[],[],[]
14,Иван Поп-Јованов,[],[],[]
15,Марко Спасић,[],[],[]
16,Милан Банковић,[],[],[]
17,Борис Цвитак,[],[],[]
18,Миодраг Живковић,[],[],[]
19,Марија Ерић,[],[],[]
20,Невена Ћирић,[],[],[]
21,Мирко Спасић,[],[],[]
22,Бојана Јошић,[],[],[]
23,Лука Јовичић,[],[],[]
24,Павле Савић,[],[],[]
25,Ирена Васиљевић,[],[],[]
26,Сташа Вујичић Станковић,[],[],[]
27,Иван Дрецун,[],[],[]
28,Младен Николић,[],[],[]
29,Милица Карличић,[],[],[]
30,Александар Вељковић,[],[],[]
31,Владимир Филиповић,[],[],[]
32,Мирослав Марић,[],[],[]
33,Милан Коцић,[],[],[]
34,Мирјана Маљковић,[],[],[]
35,Дара Милојковић,[],[],[]
36,Владимир Кузмановић,[],[],[]
37,Богдан Бадовинац,[],[],[]
38,Петар Тешић,[],[],[]
39,Милица Гњатовић,[],[],[]
40,Андрија Урошевић,[],[],[]
41,Никола Катић,[],[],[]
42,Андријана Алексић,[],[],[]
43,Нина Радојичић Матић,[],[],[]
44,Саша Малков,[],[],[]
45,Милена Стојић,[],[],[]
46,Весна Маринковић,[],[],[]
47,Вељко Милутиновић,[],[],[]
48,Страхиња Станојевић,[],[],[]
49,Милан Чугуровић,[],[],[]
50,Владан Ковачевић,[],[],[]
51,Вукан Антић,[],[],[]
52,Сана Стојановић Ђурђевић,[],[],[]
53,Иван Чукић,[],[],[]
54,Александар Картељ,[],[],[]

In [47]:
set_of_classes = set()
for i in range(df.shape[0]):
    if (df.iloc[i]['Шифра'] == df.iloc[i]['Шифра']) and (df.iloc[i]['Фонд предавања'] == df.iloc[i]['Фонд предавања']):
        set_of_classes.add((df.iloc[i]['Шифра'], int(df.iloc[i]['Фонд предавања'])))
    if df.iloc[i]['Групе В'] == df.iloc[i]['Групе В'] and int(df.iloc[i]['Групе В']) > 0 and (df.iloc[i]['Фонд вежбе'] == df.iloc[i]['Фонд вежбе']):
        set_of_classes.add((str(df.iloc[i]['Шифра']) + ' - вежбе', int(df.iloc[i]['Фонд вежбе'])))
classes = pd.DataFrame(set_of_classes, columns=['name', 'number_of_classes'])
classes['equipment'] = None

In [48]:
classes

             name  number_of_classes equipment
0    Р269 - вежбе                  3      None
1     nan - вежбе                  3      None
2           УУПУ2                  2      None
3    РМ09 - вежбе                  2      None
4            РМ15                  2      None
..            ...                ...       ...
143         УУПУ1                  2      None
144          Р231                  2      None
145          Р260                  3      None
146          РМ17                  2      None
147  РМ18 - вежбе                  2      None

[148 rows x 3 columns]

In [51]:
set_of_groups = set()
for i in range(df.shape[0]):
    if (df.iloc[i]['Ток'] == df.iloc[i]['Ток']):
        set_of_groups.add((df.iloc[i]['Ток']))
    if df.iat[i,13] == df.iat[i,13]:
        set_of_groups.add(df.iat[i,13])
groups = pd.DataFrame(set_of_groups, columns=['name'])
groups['parents'] = None

In [52]:
groups

     name parents
0   2рл1а    None
1      4и    None
2     4р3    None
3     2и1    None
4     3и1    None
..    ...     ...
77    4и2    None
78    3р2    None
79   2и2б    None
80   1и2а    None
81   3и1а    None

[82 rows x 2 columns]

In [42]:
df.iat[0,13]

'1о1а'

In [71]:
teaching_curriculum = pd.DataFrame([], columns=['lecturer', 'class', 'groups', 'groups_to_check'])

In [72]:
teaching_curriculum

Empty DataFrame
Columns: [lecturer, class, groups, groups_to_check]
Index: []

In [73]:
for i in range(df.shape[0]):
    if (df.iloc[i]['Шифра'] == df.iloc[i]['Шифра']) and (df.iloc[i]['Фонд предавања'] == df.iloc[i]['Фонд предавања']) and (df.iloc[i]['Ток'] == df.iloc[i]['Ток']) and (df.iloc[i]['Предавања'] == df.iloc[i]['Предавања']):
        teaching_curriculum.loc[len(teaching_curriculum.index)] = [df.iloc[i]['Предавања'], df.iloc[i]['Шифра'], {df.iloc[i]['Ток']}, {df.iloc[i]['Ток']}]

In [74]:
teaching_curriculum

                    lecturer    class   groups groups_to_check
0       Нина Радојичић Матић     РМ01    {1о1}           {1о1}
1   Сана Стојановић Ђурђевић     РМ02    {1о1}           {1о1}
2            Стефан Мишковић  15-РМ03   {2мнв}          {2мнв}
3               Мирко Спасић     РМ07  {2н4лв}         {2н4лв}
4    Сташа Вујичић Станковић     РМ04   {2мнв}          {2мнв}
..                       ...      ...      ...             ...
68         Александар Картељ   УУХЈВИ     {П1}            {П1}
69  Сана Стојановић Ђурђевић   УУААВИ     {П1}            {П1}
70          Мирјана Маљковић    УУДЗП     {П1}            {П1}
71   Сташа Вујичић Станковић    УУПУ1     {П1}            {П1}
72   Сташа Вујичић Станковић    УУПУ2     {П1}            {П1}

[73 rows x 4 columns]